import re
import os

filepath = 'd:/paper/scikms.py'
with open(filepath, 'r', encoding='utf-8') as f:
    text = f.read()

# Replace Import PDF with Import explicitly
text = text.replace('⬆️ Import PDF', '⬆️ Import')
text = text.replace('Import PDF', 'Import')

# Replace known Vietnamese strings
translations = {
    'Chạy:': 'Run:',
    'Yêu cầu:': 'Requirements:',
    'Tuỳ chọn cài thêm (không bắt buộc)': 'Optional dependencies',
    'CẤU HÌNH TRANG & CSS TÙNG CHỈNH': 'PAGE CONFIG & CUSTOM CSS',
    'Quản lý Y văn': 'Medical Literature Management',
    'Nền tổng thể (Light Mode)': 'Global Background (Light Mode)',
    'Dark ưu chiều rộng pages (Hoạt động trơn tru với layout="wide")': 'Optimize page width (Works smoothly with wide layout)',
    'Tùy chỉnh Sidebar': 'Customize Sidebar',
    'Deleted phần ép cứng độ rộng': 'Deleted forced width part',
    'Chống vỡ giao diện Icon Material': 'Prevent Material Icon layout break',
    'Nút bấm': 'Buttons',
    'Nền sáng, đổ bóng mềm': 'Light background, soft shadow',
    'Mặc định 2 dòng': 'Default 2 lines',
    'Trang trước': 'Previous Page',
    'Trang sau →': 'Next Page →',
    'Trang': 'Page',
    'Tổng': 'Total',
    'bài báo': 'papers',
    'bài báo nào': 'papers',
    'Từ khóa': 'Keywords',
    'Tìm kiếm Keywords': 'Search Keywords',
    'Tìm kiếm (Full-Text Search)': 'Full-Text Search',
    'Tìm kiếm': 'Search',
    'Nhập từ khóa...': 'Enter keyword...',
    'Gợi ý tag phổ biến:': 'Popular tag suggestions:',
    'Cập nhật thành công!': 'Successfully updated!',
    'Xóa thành công!': 'Successfully deleted!',
    'Tên file mới:': 'New filename:',
    'Tên gốc': 'Original name',
    'Thư viện': 'Library',
    'Chi tiết': 'Details',
    'Chưa đọc': 'Unread',
    'Đang đọc': 'Reading',
    'Đã đọc': 'Read',
    'Quay lại': 'Back',
    'Xóa bài báo': 'Delete paper',
    'Lưu ghi chú': 'Save notes',
    'Thêm mới': 'Add new',
    'Đổi tên file': 'Rename files',
    'Tùy chọn': 'Options',
    'Tìm kiếm': 'Search',
    'Chưa có dữ liệu': 'No data available',
    'Không tìm bài báo nào.': 'No papers found.',
    'Không tìm thấy bài báo nào.': 'No papers found.',
    'Không có kết quả.': 'No results.',
    'Tất cả': 'All',
    'Lưu thành công!': 'Saved successfully!',
    'Hủy': 'Cancel',
    'Sửa': 'Edit',
    'Sửa thông tin': 'Edit info',
    'Lưu': 'Save',
    'Tên bài báo': 'Paper title',
    'Tạp chí': 'Journal',
    'Ghi chú cá nhân': 'Personal notes',
    'Không có tóm tắt': 'No abstract',
    '(Mới)': '(New)',
    '(Cũ)': '(Old)',
    'Danh sách Import': 'Import List',
    'Kết quả import': 'Import results',
    'Thông tin lỗi': 'Error details',
    'Thành công': 'Success',
    'Có lỗi xảy ra': 'An error occurred',
    'Đang xử lý': 'Processing',
    'Xử lý hoàn tất': 'Processing complete',
    'Tự động tải PDF Open Access (Unpaywall) khi có DOI': 'Auto-download Open Access PDF (Unpaywall) if DOI exists',
    'Dán danh sách tài liệu tham khảo vào đây': 'Paste reference list here',
    'tài liệu tham khảo': 'references',
    'Tính năng mới!': 'New feature!',
    'dán vào đây': 'paste here',
    'hệ thống tự động phân tích từng reference': 'the system automatically parses each reference',
    'trích xuất DOI': 'extracts DOI',
    'tra cứu metadata': 'looks up metadata',
    'từ': 'from',
    'và thêm vào thư viện. Hỗ trợ định dạng': 'and adds to library. Supports format',
    'Phát hiện': 'Detected',
    'Nhấn': 'Click',
    'để thêm vào thư viện.': 'to add to library.',
    'Xem trước danh sách đã phân tích': 'Preview parsed list',
    'có DOI (se tra cuu Crossref day du)': 'have DOI (will query full Crossref)',
    'vào thu vien': 'into library',
    'tai lieu': 'references',
    'Dang import': 'Importing',
    'Da them': 'Successfully added',
    'file PDF da duoc tai va luu': 'PDF files downloaded and saved',
    'lỗi / trùng lặp': 'errors / duplicates',
    'loi / trung lap': 'errors / duplicates',
    'Không phát hiện được tài liệu tham khảo. Kiểm tra định dạng - mỗi tài liệu cần bắt đầu bằng số thứ tự': 'No references detected. Please check the format - each reference should start with a number',
    'Khong phat hien duoc tai lieu tham khao': 'No references detected',
    'Kiem tra dinh dang - moi tai lieu can bat dau bang so thu tu': 'Check format - each reference should start with a number',
    'Import từ DOI': 'Import from DOI',
    'Import tu DOI': 'Import from DOI',
    'Đang tra cứu metadata từ Crossref...': 'Looking up metadata from Crossref...',
    'Đã thêm vào thư viện!': 'Added to library!',
    'PDF OA đã tải về': 'OA PDF downloaded',
    'Tìm thấy link PDF nhưng không tải được.': 'Found PDF link but cannot download.',
    'Mở link': 'Open link',
    'Không tìm thấy PDF Open Access': 'No Open Access PDF found',
    'Kết quả lần xử lý gần nhất': 'Latest processing results',
    'và': 'and',
    'bài khác': 'more papers',
    'bài khac': 'more papers',
    'TIỆN ÍCH XỬ LÝ FILE': 'FILE PROCESSING UTILITIES',
    'Chuẩn hoá chuỗi thành tên file an toàn.': 'Normalize string to safe filename.',
    'Rút họ tác giả': 'Extract author last names',
    'Dạng "Last, First" hoặc "First Last"': 'Format "Last, First" or "First Last"',
    'Rút 5-6 từ đầu tiêu đề': 'Extract first 5-6 words of title',
    'Đổi tên file vật lý trên ổ cứng và trả về đường dẫn mới.': 'Rename physical file on disk and return new path.',
    'Có xử lý chống ghi đè nếu trùng tên.': 'Includes collision handling.',
    'Lấy thư mục chứa file hiện tại (thường là "storage")': 'Get directory containing current file (usually "storage")',
    'Tạo đường dẫn mới': 'Create new path',
    'Chống trùng lặp tên file (nếu 2 papers có cùng năm, cùng tác giả, cùng tiêu đề rút gọn)': 'Prevent filename collisions (if 2 papers have same year, author, title)',
    'Đổi tên file thực tế': 'Rename actual file',
    'Tìm kiếm bài báo qua PubMed E-utilities API (miễn phí, không cần key).': 'Search papers via PubMed E-utilities API (free, no key).',
    'Hỗ trợ: tìm theo PMID, DOI, hoặc chuỗi tìm kiếm tự do.': 'Supports: search by PMID, DOI, or free search string.',
    'Trả về dict giống format fetch_crossref().': 'Returns dict like fetch_crossref().',
    'Bước 1: Lấy PMID ──────────────────────────────────────────────': 'Step 1: Get PMID ──────────────────────────────────────────────',
    'Tìm theo DOI hoặc chuỗi query': 'Search by DOI or query string',
    'Bước 2: Fetch chi tiết bài báo qua efetch ─────────────────────': 'Step 2: Fetch paper details via efetch ─────────────────────',
    'Trích xuất nội dung tag XML đơn giản.': 'Extract simple XML tag content.',
    'DOI từ ArticleId': 'DOI from ArticleId',
    'Import bài báo từ PMID vào thư viện.': 'Import paper from PMID to library.',
    'PMID phải là số nguyên (ví dụ: 17532924)': 'PMID must be an integer (e.g., 17532924)',
    'Kiểm tra duplicate': 'Check duplicates',
    'PubMed không lưu pmid trực tiếp, kiểm tra qua notes hoặc doi': 'PubMed does not store pmid directly, check via notes or doi',
    'PMID đã tồn tại:': 'PMID already exists:',
    'Không tìm thấy metadata cho PMID:': 'Metadata not found for PMID:',
    'Nếu có DOI, thử dùng Crossref để lấy thêm': 'If DOI exists, try using Crossref to get more',
    'Thử thêm qua PMC': 'Try adding via PMC',
    'Bài báo đã tồn tại (duplicate MD5).': 'Paper already exists (duplicate MD5).',
    'Tìm link PDF Open Access miễn phí qua Unpaywall API. Trả về URL PDF nếu có.': 'Find free Open Access PDF link via Unpaywall API. Returns PDF URL if available.',
    'Tìm link PDF Open Access qua Semantic Scholar API.': 'Find Open Access PDF link via Semantic Scholar API.',
    'Hỗ trợ tìm theo DOI hoặc tiêu đề bài báo.': 'Supports searching by DOI or paper title.',
    'Ưu tiên tìm theo DOI': 'Prioritize searching by DOI',
    'Fallback: tìm theo tiêu đề': 'Fallback: search by title',
    'Tìm link PDF miễn phí từ PubMed Central (PMC).': 'Find free PDF link from PubMed Central (PMC).',
    'Trả về URL tải PDF nếu bài báo có trong PMC.': 'Returns PDF download URL if paper is in PMC.',
    'Lấy PMCID từ DOI hoặc PMID': 'Get PMCID from DOI or PMID',
    'PMC PDF link trực tiếp': 'Direct PMC PDF link',
    'Tìm PDF Open Access từ nhiều nguồn theo thứ tự ưu tiên:': 'Find Open Access PDF from multiple sources in order of priority:',
    '1. Unpaywall  2. Semantic Scholar  3. PubMed Central': '1. Unpaywall  2. Semantic Scholar  3. PubMed Central',
    'Lưu bytes PDF vào storage và trích xuất metadata.': 'Save PDF bytes to storage and extract metadata.',
    'Hàm nội bộ dùng chung cho cả tải từ URL và xử lý bytes trực tiếp.': 'Internal function shared for both URL download and direct bytes processing.',
    'Xác thực đây là PDF hợp lệ': 'Validate this is a valid PDF',
    'Không phải file PDF hợp lệ hoặc file quá nhỏ': 'Not a valid PDF file or file too small',
    'Truyền bytes trực tiếp — không đọc lại từ disk': 'Pass bytes directly — do not read from disk again',
    'Tải PDF từ URL và lưu vào storage.': 'Download PDF from URL and save to storage.',
    'requests chưa cài hoặc URL trống': 'requests not installed or URL empty',
    'Chấp nhận nếu header có pdf hoặc magic bytes có %PDF': 'Accept if header has pdf or magic bytes has %PDF',
    'Response không phải PDF': 'Response is not PDF',
    'Timeout khi tải PDF (30s)': 'Timeout when downloading PDF (30s)',
    'Lưu PDF từ bytes đã có sẵn (ví dụ: file upload) — không cần tải lại.': 'Save PDF from existing bytes (e.g., file upload) — no need to download again.',
    'Tạo bản ghi paper từ DOI mà không cần file PDF.': 'Create paper record from DOI without PDF file.',
    'Dùng Crossref để lấy metadata, Unpaywall để tìm PDF OA.': 'Use Crossref for metadata, Unpaywall to find OA PDF.',
    'Kiểm tra duplicate DOI': 'Check duplicate DOI',
    'DOI đã tồn tại trong thư viện: «{exists[\'title\']}»': 'DOI already exists in library: «{exists[\'title\']}»',
    'Lấy metadata từ Crossref': 'Get metadata from Crossref',
    'Không tìm thấy metadata cho DOI:': 'Metadata not found for DOI:',
    'Kiểm tra lại DOI.': 'Please check DOI.',
    'Thử tìm và tải PDF Open Access từ nhiều nguồn': 'Try finding and downloading Open Access PDF from multiple sources',
    'Tính MD5: dùng file nếu có, ngược lại dùng DOI': 'Calculate MD5: use file if available, otherwise use DOI',
    'Bài báo đã tồn tại trong thư viện (duplicate).': 'Paper already exists in library (duplicate).',
    'Tạo chuỗi trích dẫn chuẩn.': 'Generate standard citation string.',
    'Kiểm tra trùng lặp thông minh theo DOI hoặc độ tương đồng tiêu đề.': 'Smart duplicate check by DOI or title similarity.',
    'Trả về paper đã tồn tại nếu trùng, None nếu không.': 'Returns existing paper if duplicated, None otherwise.',
    'Dùng context manager để đảm bảo connection luôn được đóng.': 'Use context manager to ensure connection is always closed.',
    'Kiểm tra DOI trước': 'Check DOI first',
    'Kiểm tra title gần giống (Jaccard similarity)': 'Check similar title (Jaccard similarity)',
    'Tính độ tương đồng đơn giản giữa 2 chuỗi (Jaccard token similarity).': 'Calculate simple similarity between 2 strings (Jaccard token similarity).',
    'Lấy danh sách projects từ DB.': 'Get list of projects from DB.',
    'Trích xuất text + metadata từ PDF bằng PyMuPDF.': 'Extract text + metadata from PDF using PyMuPDF.',
    'Giới hạn 20 pages đầu để tiết kiệm bộ nhớ': 'Limit first 20 pages to save memory',
    'Rút keywords từ metadata hoặc từ text': 'Extract keywords from metadata or text',
    'Rút tác giả từ PDF metadata': 'Extract authors from PDF metadata',
    'Nếu không có trong metadata, thử regex trên đoạn đầu': 'If not in metadata, try regex on first segment',
    'Thử pattern:': 'Try pattern:',
    'hoặc dòng sau tiêu đề trước abstract': 'or line after title before abstract',
    'tác\\s*giả': 'author',
    'Abstract extraction – Dark ưu hoá tránh lỗi ReDoS (Freezing) ─────────────────': 'Abstract extraction - Dark optimized to avoid ReDoS (Freezing) ─────────────────',
    'Tìm vị trí bắt đầu của Abstract': 'Find start position of Abstract',
    'tóm tắt': 'abstract',
    'Tìm vị trí kết thúc (dựa vào các tiêu đề theo sau phổ biến)': 'Find end position (based on common following titles)',
    'Tìm marker gần nhất xuất hiện SAU abstract': 'Find nearest marker appearing AFTER abstract',
    'Bỏ qua 10 ký tự đầu để tránh match chính nó': 'Skip first 10 chars to avoid matching itself',
    'Trích xuất nếu độ dài hợp lý (tránh lấy cả bài)': 'Extract if length is reasonable (avoid taking whole paper)',
    'Lấy nguyên bản text (để giữ hoa/thường)': 'Get original text (to preserve case)',
    'Loại bỏ chữ "Abstract" hoặc "Abstract" ở đầu': 'Remove "Abstract" at the beginning',
    'tóm\\s*tắt': 'abstract',
    'Dọn dẹp khoảng trắng': 'Clean whitespaces',
    'Giới hạn độ dài hợp lý': 'Limit reasonable length',
    'Rút keywords từ text nếu chưa có': 'Extract keywords from text if not present',
    'Giới hạn 50k ký tự': 'Limit 50k characters',
    'Dùng Gemini AI để trích xuất metadata từ pages đầu papers.': 'Use Gemini AI to extract metadata from first pages of papers.',
    'Thất bại thầm lặng nếu không có API key': 'Fail silently if no API key',
    'Tag dictionary mặc định (Plastic / Reconstructive Surgery) ──────────────': 'Default Tag dictionary (Plastic / Reconstructive Surgery) ──────────────',
    'Nội khoa / tổng quát': 'Internal medicine / general',
    'Đọc từ điển tag tùy chỉnh từ config. Fallback về dict mặc định.': 'Read custom tag dict from config. Fallback to default dict.',
    'Lưu từ điển tag tùy chỉnh vào config.': 'Save custom tag dict to config.',
    'Tự động gắn tag từ từ điển chuyên ngành (có thể tùy chỉnh).': 'Auto-tag from specialized dictionary (customizable).',
    'Tối đa 10 tags': 'Max 10 tags',
    'Logic bọc hậu: Phân tích khối Header của papers.': 'Fallback logic: Analyze Header block of papers.',
    'Chỉ dùng khi Regex cơ bản không tìm thấy tác giả/tiêu đề.': 'Only use when basic Regex cannot find author/title.',
    'Cắt lấy phần "Header" (từ đầu đến trước chữ Abstract/Introduction)': 'Extract "Header" part (from beginning to before Abstract/Introduction text)',
    'Tập từ khóa nhận diện rác (thông tin xuất bản)': 'Junk keyword set (publication info)',
    'Tập từ khóa nhận diện Cơ quan/Đơn vị công tác (Affiliation) - Hỗ trợ cả English & Việt': 'Affiliation keyword set - Supports both English & Vietnamese',
    'đại\\s*học': 'university',
    'bệnh\\s*viện': 'hospital',
    'khoa\\s+': 'department ',
    'viện\\s+': 'institute ',
    'Tìm Title: Thường là dòng dài đầu tiên, không chứa từ khóa cơ quan': 'Find Title: Usually the first long line, not containing affiliation keywords',
    'Title thường có nhiều hơn 2 từ': 'Title usually has more than 2 words',
    'Tìm Authors: Các dòng ngay dưới tiêu đề, dừng lại khi gặp cơ quan': 'Find Authors: Lines right below title, stop when hitting affiliation keyword',
    'Nếu đụng dòng chứa tên Bệnh viện, Khoa, Trường -> bỏ qua': 'If hitting line containing Hospital, Department, School -> skip',
    'Tên người thường nằm ở dòng không quá dài': 'Person names usually in lines not too long',
    'Dọn dẹp dứt điểm các số mũ, chữ cái mũ chú thích (VD: Ball¹, Nguyen^a, Tran*)': 'Clean up superscript numbers, footnote letters (e.g., Ball¹, Nguyen^a, Tran*)',
    'Loại bỏ các chữ cái a, b, c đứng liền sát dấu phẩy (VD: Smith a, Jones b)': 'Remove letters a, b, c next to commas (e.g., Smith a, Jones b)',
    'Tách tên bằng phẩy, "and", "&"': 'Split names by comma, "and", "&"',
    'Trích xuất siêu mạnh mẽ chuyên dụng cho pages bìa Luận án/Luận văn tiếng Việt.': 'Powerful extraction specialized for Vietnamese Thesis covers.',
    'Bắt chính xác Title nhiều dòng, dọn dẹp sạch sẽ học hàm/học vị, và lấy được Year chuẩn xác.': 'Accurately captures multi-line Title, cleans degrees/titles, and gets accurate Year.',
    'LẤY NĂM BẢO VỆ/XUẤT BẢN (NÂNG CẤP)': 'GET DEFENSE/PUBLICATION YEAR (UPGRADED)',
    'Ưu tiên 1: Tìm các mẫu rõ ràng ở cuối pages như': 'Priority 1: Find clear patterns at end of pages like',
    'Ưu tiên 2: Tìm tất cả các năm (từ 1950 - 2030) và lấy năm CUỐI CÙNG xuất hiện trên pages bìa': 'Priority 2: Find all years (1950 - 2030) and get LAST year on cover page',
    'Lấy phần tử cuối cùng vì năm bảo vệ luôn ở cuối pages': 'Get last element because defense year is always at end of pages',
    'TÌM TÁC GIẢ VÀ DỌN DẸP HỌC VỊ': 'FIND AUTHOR AND CLEAN DEGREES',
    'nghiên cứu sinh': 'phd student',
    'học viên': 'student',
    'sinh viên': 'student',
    'tác giả': 'author',
    'người thực hiện': 'executor',
    'họ và tên(?:\\s*(?:ncs|học viên|sinh viên))?': 'full name(?:\\s*(?:phd student|student))?',
    'họ tên': 'full name',
    'Nếu nhãn ở 1 dòng và tên rớt xuống dòng dưới': 'If label is on 1 line and name drops to next line',
    'Dọn dẹp triệt để các combo học hàm/học vị dính liền (VD: "PGS.TS.BS.", "ThS.BS")': 'Thoroughly clean combined degree abbreviations (e.g., "PGS.TS.BS.", "ThS.BS")',
    'Dùng vòng lặp để gọt sạch nếu có nhiều học vị nối tiếp nhau': 'Use loop to clean string if multiple consecutive degrees exist',
    'TÌM TIÊU ĐỀ LUẬN ÁN/BÀI BÁO': 'FIND THESIS/PAPER TITLE',
    'BỘ GIÁO DỤC': 'MINISTRY OF EDUCATION',
    'BỘ Y TẾ': 'MINISTRY OF HEALTH',
    'ĐẠI HỌC': 'UNIVERSITY',
    'TRƯỜNG': 'SCHOOL',
    'VIỆN': 'INSTITUTE',
    'LUẬN ÁN': 'THESIS',
    'LUẬN VĂN': 'DISSERTATION',
    'KHOÁ LUẬN': 'THESIS',
    'BÁO CÁO': 'REPORT',
    'CHUYÊN NGÀNH': 'MAJOR',
    'MÃ SỐ': 'CODE',
    'NGƯỜI HƯỚNG DẪN': 'SUPERVISOR',
    'THÀNH PHỐ': 'CITY',
    'CHUYÊN KHOA': 'SPECIALTY',
    'CÁN BỘ': 'OFFICIAL',
    'BỘ QUỐC PHÒNG': 'MINISTRY OF DEFENSE',
    'Kịch bản 1: Bắt theo mỏ neo "ĐỀ TÀI"': 'Scenario 1: Capture by "TOPIC" anchor',
    'Càn quét các dòng bên dưới để ghép nối tiêu đề (tối đa 6 dòng)': 'Scan below lines to concatenate title (max 6 lines)',
    'hướng dẫn': 'supervisor',
    'Kịch bản 2: Không có chữ ĐỀ TÀI, tìm khối chữ IN HOA dài nhất': 'Scenario 2: Without TOPIC word, find longest UPPERCASE block',
    'Dòng tiêu đề thường viết hoa, dài hơn 2 từ và không chứa rác': 'Title line usually uppercase, longer than 2 words, no junk',
    'Kiểm tra xem title lấy từ pdf properties có phải là rác không': 'Check if title from pdf properties is garbage',
    'Kiểm tra xem author lấy từ pdf properties có phải là rác không': 'Check if author from pdf properties is garbage',
    'Pipeline xử lý PDF files upload.': 'Pipeline for processing uploaded PDF files.',
    'Kiểm tra trùng lặp (MD5 hash)': 'Check duplicate (MD5 hash)',
    'File đã tồn tại trong thư viện (MD5: {md5[:8]}…)': 'File already exists in library (MD5: {md5[:8]}…)',
    'Trích xuất từ PDF': 'Extract from PDF',
    'Bước 1: Tìm DOI': 'Step 1: Find DOI',
    'Bước 2: Gọi Crossref nếu có DOI': 'Step 2: Call Crossref if DOI exists',
    'Bước 3: Dùng dữ liệu PDF metadata nếu chưa đủ (Có màng lọc chống rác)': 'Step 3: Use PDF metadata if insufficient (With junk filter)',
    'Ưu tiên author từ PDF metadata nhưng phải qua kiểm duyệt': 'Prioritize author from PDF metadata but must be checked',
    'BƯỚC 3.5: LOGIC BỌC HẬU (Fallback Heuristic)': 'STEP 3.5: FALLBACK HEURISTIC',
    'Chỉ chạy khi Regex cũ không bắt được Title hoặc Authors': 'Only run when old Regex fails to capture Title or Authors',
    'Chỉ bổ sung vào các trường đang trống': 'Only supplement into empty fields',
    'BƯỚC 3.6: LOGIC CHUYÊN DỤNG CHO LUẬN ÁN/TÀI LIỆU TIẾNG VIỆT': 'STEP 3.6: SPECIALIZED LOGIC FOR VIETNAMESE THESIS/DOCUMENTS',
    'Nhận diện đặc điểm của tài liệu VN (Luận án, Y tế, Giáo dục...)': 'Identify characteristics of VN docs (Thesis, Health, Education...)',
    'Ghi đè hoặc bổ sung thông tin': 'Overwrite or supplement information',
    'Bước 4: Gemini AI fallback – khi thiếu title hoặc authors': 'Step 4: Gemini AI fallback - when title or authors are missing',
    'Bước 5: Fallback thông minh từ tên file': 'Step 5: Smart fallback from filename',
    'KIỂM TRA TRÙNG LẶP THÔNG MINH (DOI + Tiêu đề) ────────────────────────': 'SMART DUPLICATE CHECK (DOI + Title) ────────────────────────',
    'phát hiện bài báo trùng lặp ({match_reason}):': 'Duplicate paper detected ({match_reason}):',
    'Tiêu đề tương tự': 'Similar title',
    'Tự động gắn tags từ từ điển chuyên ngành': 'Auto-attach tags from specialized dictionary',
    'Lấy keywords từ AI hoặc PDF metadata (ưu tiên AI)': 'Get keywords from AI or PDF metadata (prioritize AI)',
    'Bộ lọc rác: Chặn các từ khóa chứa tên cơ quan, học vị hoặc ngày tháng': 'Junk filter: Block keywords containing affiliation, degree or date',
    'Kiểm tra điều kiện loại trừ:': 'Check exclusion conditions:',
    '1. Chứa từ rác': '1. Contains junk word',
    '2. Là chuỗi ngày tháng (vd: 09 Jun 2020)': '2. Is date string (e.g. 09 Jun 2020)',
    '3. Quá dài (>45 ký tự thường là một câu văn chứ không phải keyword)': '3. Too long (>45 chars is usually a sentence not keyword)',
    'Ghi vào DB': 'Write to DB',
    'Các cột cần thiết cho list view — bỏ full_text để giảm RAM': 'Columns needed for list view - exclude full_text to reduce RAM',
    'Load tất cả papers nhưng bỏ cột full_text để tiết kiệm RAM.': 'Load all papers but exclude full_text to save RAM.',
    'Dùng cho Library, Search, Sidebar stats. TTL=30s.': 'Used for Library, Search, Sidebar stats. TTL=30s.',
    'Load một paper đầy đủ bao gồm full_text — chỉ dùng khi cần đọc.': 'Load full paper including full_text - only used when reading.',
    'Đếm số papers — không load dữ liệu.': 'Count number of papers - avoid loading data.',
    'Load papers theo trang — dùng cho Library với thư viện lớn.': 'Load papers by page - used for Library with large collection.',
    'Whitelist các cột hợp lệ trong bảng papers - bảo vệ khỏi SQL injection': 'Whitelist valid columns in papers table - protect against SQL injection',
    'Cập nhật paper an toàn với whitelist cột tường minh.': 'Safely update paper with explicit column whitelist.',
    'Lọc chỉ giữ các cột hợp lệ — ngăn SQL injection qua tên cột': 'Filter to keep only valid columns - prevent SQL injection via column name',
    'Tìm kiếm full-text với SQLite FTS5. Fallback về LIKE nếu lỗi.': 'Full-text search with SQLite FTS5. Fallback to LIKE if errors.',
    'Trả về list dicts không chứa full_text để tiết kiệm RAM.': 'Returns list of dicts without full_text to save RAM.',
    'Sanitize: giữ ký tự alphanumeric + khoảng trắng, loại dấu FTS5 đặc biệt': 'Sanitize: keep alphanumeric + whitespace, remove special FTS5 chars',
    'Thêm * để prefix-match (ví dụ "rhinop" → "rhinoplasty")': 'Add * for prefix-match (e.g. "rhinop" -> "rhinoplasty")',
    'Fallback: LIKE search trên các cột quan trọng (không full_text)': 'Fallback: LIKE search on important columns (not full_text)',
    'Tô màu từ khóa trong đoạn text, rút gọn cho preview.': 'Highlight keywords in text snippet, truncate for preview.',
    'Xuất bảng tóm tắt ra Excel với định dạng đẹp.': 'Export summary table to Excel with nice formatting.',
    'Màu sắc header': 'Header colors',
    'Dữ liệu': 'Data',
    'Độ rộng cột tự động': 'Auto column width',
    'Stats nhỏ': 'Small stats',
    'Bộ lọc nhanh': 'Quick filters',
    'HÀM HIỂN THỊ CARD BÀI BÁO': 'PAPER CARD DISPLAY FUNCTION',
    'Mở link →': 'Open link →',
    'Trang trước': 'Previous Page',
    'Trang sau →': 'Next Page →',
    'Tổng': 'Total',
    'bài báo': 'papers',
    'Từ khóa': 'Keywords',
    'Năm': 'Year',
    'Tác giả': 'Authors',
    'Ghi chú': 'Notes',
    'Thư viện': 'Library',
    'Mô tả': 'Description',
    'Tài liệu tham khảo': 'References',
    'Tìm kiếm': 'Search',
    'Gợi ý tag phổ biến': 'Popular tag suggestions',
    'Xem trước danh sách đã phân tích': 'Preview parsed list',
    'Hoàn tất!': 'Complete!',
    'bài báo trùng lặp': 'duplicate paper',
    'Đã thêm vào thư viện!': 'Added to library!',
    '✅ Saved!': '✅ Saved!',
    'Tên bài báo': 'Paper Title',
    'Tạp chí': 'Journal',
    'Phân tách bằng': 'Separated by',
    'phân tách bằng': 'separated by',
}

for k, v in translations.items():
    text = text.replace(k, v)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(text)

print("done")
